### PR TITLE
Merge main in dev

### PR DESCRIPTION
**Pull request by NormalNickYT**
### Checklist

- [ ] Tests have been written/updated (if necessary)
  - [ ] All tests are passing
- [ ] Docs have been updated (if necessary)
- [ ] Updated `Linear` issue to `In Review`

### Description

Merge main in dev

### CODE REVIEW

**Review by jortdr — COMMENTED** [review]
@n-vr is this supposed to be done like this? What will the next version be called?

**Comment by n-vr** [comment]
@jortdr do you mean by "is it supposed to be done like this?", the fact that you need to create a PR from main to dev to bring it up-to-date before you can merge dev to main?

In that case, I think you briefly had to because of some restrictions I set. But I think I relaxed those, so you should be able to do this the same way you used to do it.

And what do you mean by "what will the next version be called"?

**Comment by jortdr** [comment]
@n-vr 
What I mean is that we need to up the version number to the current release so the semantic release bot doesn't get confused.

What will the next version number be? 2.10.1? still 2.9.x? You told me that there was an issue releasing last time with the release bot giving a wrong version.

**Comment by n-vr** [comment]
@jortdr I can't racall that I told you that. I did tell @NormalNickYT not to worry that we are already at v2.10.0 now, even though we had a Trello card somewhere that said "release v2.10.0 as production version" and this is not yet targeting production.

The version numbers as they are, are correct. Just let the semantic version action decide the next version and we'll be fine.

I'll merge this PR so you can continue.

**Pull request merged**
