### PR TITLE
fixed possibility that resolvedLanguage is undefined

### PR DESCRIPTION
**Pull request by NormalNickYT**
### Checklist

- [ ] Tests have been written/updated (if necessary)
  - [ ] All tests are passing
- [ ] Docs have been updated (if necessary)
- [ ] Updated `Linear` issue to `In Review`

### Description

fix: possibility that resolvedLanguage is undefined

### CODE REVIEW

**Review by NormalNickYT — COMMENTED** [review]
Here we still use manuals.tst tho, and Nick just made a pull-request where tst is removed.

**Comment by n-vr** [comment]
That's fine @NormalNickYT

**Review by n-vr — APPROVED** [review]
Seems a bit verbose/duplicated like this, but looks like it will fix the problem. 👍

**Comment by NormalNickYT** [comment]
@n-vr 

Yes it was a fast solution. I'll include this in our backlog for enhancing the code's reusability.

**Review by CodingMoonMan — APPROVED** [review]
LGTM

**Pull request merged**
