### PR TITLE
Features added for new release

### PR DESCRIPTION
**Pull request by NormalNickYT**
### Checklist

- [ ] Tests have been written/updated (if necessary)
  - [ ] All tests are passing
- [ ] Docs have been updated (if necessary)
- [ ] Updated `Linear` issue to `In Review`

### Description
The following bugs / functionalities have been added: 
 - Combine list of cloud feeds into into the device list overview
 - Fix building numbers shown on 'Measurements' screen
 - Fix 4th tick after WiFi reset: upload date needs to be newer than time of reset
 - Fix app waiting indefinitely at 4th step after Wi-Fi reset

### CODE REVIEW

**Review by jortdr — COMMENTED** [review]
Looks good to me.

**Review by n-vr — CHANGES_REQUESTED** [review]
Not all commit messages follow conventional commit practices. Do you want to update them or should I?

**Comment by n-vr** [comment]
I force pushed a rebase to change commit messages for some commits. The messages adhere to conventional commits now, and will be used in the changelog for the new version.

**Review by n-vr — APPROVED** [review]
If you are OK with the commit messages now, you can merge this.

**Pull request merged**
